### ISSUE TITLE
Unable to revive/respawn.

### ISSUE THREAD

**Issue by StuxxyOfficial** [d3rp-jsx/esx_healthnarmour#2]
Not sure if this issue is unique to myself but i haven't edited anything. 

When a player is dead  and they crash or disconnect or the server restarts, it stores there health as 0, when a character respawns it is immediately set back to 0 so the player drops back into ragdoll

I can't see what im doing wrong?

im using a vanilla es_extended, latest version etc.

**Comment by d3rp-jsx** [comment]
It's fixed on latest commit. Please be sure to reset health manually for the ones who are already dead and it should never happen again.

**Comment by d3rp-jsx** [comment]
It's not completely fixed, I'll check this out tomorrow, thanks for reporting.

**Comment by d3rp-jsx** [comment]
Fixed now
